server:
  port: 8085

spring:
  application.name: transaction
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari.connectionTimeout: 10000
    hikari.maximumPoolSize: 5
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB} # if it does not exist, will create one
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resource:
      add-mappings: false
  jpa:
    hibernate.ddl-auto: update
  kafka:
    consumer:
      bootstrap-server: ${KAFKA_SERVER}
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-server: ${KAFKA_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  db.init.enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Blockchain RPC configuration
blockchain:
  rpc:
    ethereum: ${BLOCKCHAIN_RPC_ETHEREUM}
    solana: ${BLOCKCHAIN_RPC_SOLANA}
    bsc: ${BLOCKCHAIN_RPC_BSC}
    sui: ${BLOCKCHAIN_RPC_SUI}
  polling:
    interval: ${BLOCKCHAIN_POLLING_INTERVAL}

# Prometheus endpoint configuration
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web: # Enable more detailed metrics
      server:
        request:
          autotime:
            enabled: true
